openapi: 3.0.0
info:
  title: File Manager API
  version: 0.0.1
  description: API for managing files
servers:
  - url: http://localhost:8080
paths:
  /contents:
    get:
      security:
        - bearerAuth: []
      summary: Get the contents of a directory
      operationId: getHomeDirectory
      responses:
        '200':
          description: A list of files and directories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
    post:
      security:
        - bearerAuth: []
      summary: Create a new directory
      operationId: CreateContent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new content
                parentID:
                  type: string
                  format: uuid
                  description: The parent directory of the new content
                type:
                  type: string
                  description: The type of the new content
              required:
                - name
      responses:
        '200':
          description: The newly created directory
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Content:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the content
        name:
          type: string
          description: The name of the content
        parentID:
          type: string
          format: uuid
          description: The parent directory of the content
        type:
          type: string
          description: The type of the content
      required:
        - id
        - name
        - parentID
        - type
