openapi: 3.0.0
servers:
  - url: http://localhost:8080
info:
  title: File Manager API
  version: 0.0.1
  description: API for managing files

paths:
  /contents:
    get:
      security:
        -  bearerAuth: []
      summary: Get the contents of a directory
      operationId: getHomeDirectory
      responses:
        '200':
          description: A list of files and directories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: schema/content.yaml#/components/schemas/Content

    post:
      security:
        -  bearerAuth: []
      summary: Create a new directory
      operationId: CreateContent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new content
                parentID:
                  type: string
                  format: uuid
                  description: The parent directory of the new content
                type:
                  type: string
                  description: The type of the new content
              required:
                - name
      responses:
        '200':
          description: The newly created directory
          content:
            application/json:
              schema:
                type: string

  /content/{id}:
    get:
      security:
        -  bearerAuth: []
      summary: Get the content by ID
      operationId: getContentByID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the content
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The content
          content:
            application/json:
              schema:
                $ref: schema/content.yaml#/components/schemas/Content


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT